#!/usr/bin/env python3
"""Read-only K2 Pro Combo G-code preflight.

The scanner checks stored G-code for duplicate start/mesh commands, CFS-hostile
M600 usage, invalid tool numbers, missing preview/progress metadata, adaptive
mesh object metadata, and implausible pressure-advance commands. It never
modifies a file and never sends G-code to the printer.
"""

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path


GCODE_DIR = Path(
    os.environ.get("K2_GCODE_PREFLIGHT_DIR", "/mnt/UDISK/printer_data/gcodes")
)
BUILD = "k2-gcode-preflight-1.0"
TOOL_RE = re.compile(r"^T(\d+)$", re.I)
ADVANCE_RE = re.compile(r"(?:^|\s)ADVANCE\s*=\s*([-+]?\d+(?:\.\d+)?)", re.I)
TOTAL_LAYER_MARKERS = (
    "total layer number:",
    "total layers count =",
    "total_layer_count",
    "layer_count:",
)
THUMBNAIL_MARKERS = (
    "thumbnail begin",
    "thumbnail_jpg begin",
    "thumbnail_block_start",
    "png begin",
)


def command_from_line(line):
    stripped = line.lstrip("\ufeff \t\r\n")
    if not stripped or stripped.startswith(";"):
        return "", ""
    command_text = stripped.split(";", 1)[0].strip()
    if not command_text:
        return "", ""
    token = command_text.split(None, 1)[0].upper()
    return token, command_text


def add_finding(findings, level, code, message, line=None):
    row = {"level": level, "code": code, "message": message}
    if line is not None:
        row["line"] = int(line)
    findings.append(row)


def scan_file(path, assume_cfs=True):
    target = Path(path)
    result = {
        "build": BUILD,
        "file": target.name,
        "path": str(target),
        "size_bytes": target.stat().st_size if target.is_file() else None,
        "generated_by": None,
        "commands": {
            "start_print": 0,
            "g29": 0,
            "bed_mesh_calibrate": 0,
            "m600": 0,
            "tool_commands": 0,
            "exclude_object_define": 0,
            "pressure_advance": 0,
        },
        "metadata": {
            "thumbnail": False,
            "total_layers": False,
            "estimated_time": False,
            "filament_usage": False,
        },
        "tools": [],
        "pressure_advance_values": [],
        "findings": [],
        "safety": "read_only_no_file_changes_no_gcode_submission",
    }
    findings = result["findings"]
    if not target.is_file():
        add_finding(findings, "FAIL", "FILE_MISSING", "G-code file does not exist")
        return result
    if target.suffix.lower() not in (".gcode", ".gco", ".gc"):
        add_finding(
            findings,
            "WARN",
            "EXTENSION_UNUSUAL",
            "file extension is not a normal G-code extension",
        )

    first_start_line = None
    first_tool_line = None
    dangerous_commands = []
    tools = set()
    try:
        with target.open("r", encoding="utf-8", errors="ignore") as handle:
            for line_number, line in enumerate(handle, 1):
                lower = line.lower()
                if line.lstrip().startswith(";"):
                    if result["generated_by"] is None and "generated by " in lower:
                        result["generated_by"] = line.strip()[1:].strip()[:160]
                    if any(marker in lower for marker in THUMBNAIL_MARKERS):
                        result["metadata"]["thumbnail"] = True
                    if any(marker in lower for marker in TOTAL_LAYER_MARKERS):
                        result["metadata"]["total_layers"] = True
                    if "estimated printing time" in lower or "estimated_time" in lower:
                        result["metadata"]["estimated_time"] = True
                    if "filament used" in lower or "filament_used" in lower:
                        result["metadata"]["filament_usage"] = True
                    continue

                token, command_text = command_from_line(line)
                if not token:
                    continue
                if token == "START_PRINT":
                    result["commands"]["start_print"] += 1
                    if first_start_line is None:
                        first_start_line = line_number
                elif token == "G29":
                    result["commands"]["g29"] += 1
                elif token == "BED_MESH_CALIBRATE":
                    result["commands"]["bed_mesh_calibrate"] += 1
                elif token == "M600":
                    result["commands"]["m600"] += 1
                elif token == "EXCLUDE_OBJECT_DEFINE":
                    result["commands"]["exclude_object_define"] += 1
                elif token == "SET_PRESSURE_ADVANCE":
                    result["commands"]["pressure_advance"] += 1
                    match = ADVANCE_RE.search(command_text)
                    if match:
                        result["pressure_advance_values"].append(
                            {"line": line_number, "value": float(match.group(1))}
                        )
                    else:
                        add_finding(
                            findings,
                            "WARN",
                            "PA_VALUE_UNREADABLE",
                            "SET_PRESSURE_ADVANCE has no readable ADVANCE value",
                            line_number,
                        )

                tool_match = TOOL_RE.match(token)
                if tool_match:
                    tool = int(tool_match.group(1))
                    result["commands"]["tool_commands"] += 1
                    tools.add(tool)
                    if first_tool_line is None:
                        first_tool_line = line_number
                if token.startswith("BOX_") or token == "M8200":
                    dangerous_commands.append({"line": line_number, "command": token})
    except OSError as exc:
        add_finding(findings, "FAIL", "FILE_READ_FAILED", str(exc))
        return result

    result["tools"] = sorted(tools)
    commands = result["commands"]
    direct_mesh_count = commands["g29"] + commands["bed_mesh_calibrate"]

    if commands["start_print"] > 1:
        add_finding(
            findings,
            "WARN",
            "START_PRINT_DUPLICATE",
            "START_PRINT appears %d times as executable G-code" % commands["start_print"],
        )
    elif commands["start_print"] == 1:
        add_finding(findings, "OK", "START_PRINT_SINGLE", "one executable START_PRINT is present")
    else:
        add_finding(
            findings,
            "INFO",
            "START_PRINT_MISSING",
            "no START_PRINT command is present; this may be intentional for a factory file",
        )

    if direct_mesh_count > 1:
        add_finding(
            findings,
            "WARN",
            "MESH_COMMAND_DUPLICATE",
            "direct G29/BED_MESH_CALIBRATE appears %d times" % direct_mesh_count,
        )
    if commands["start_print"] and direct_mesh_count:
        add_finding(
            findings,
            "WARN",
            "MESH_WITH_START_PRINT",
            "direct mesh command is combined with START_PRINT and may duplicate K2/KAMP meshing",
        )
    elif direct_mesh_count <= 1:
        add_finding(
            findings,
            "OK",
            "MESH_SEQUENCE_NO_DUPLICATE",
            "no duplicate direct mesh sequence was found",
        )

    if assume_cfs and commands["m600"]:
        add_finding(
            findings,
            "WARN",
            "M600_WITH_CFS",
            "M600 appears %d times; K2 Pro Combo should use slicer tool changes/Creality CFS"
            % commands["m600"],
        )
    elif not commands["m600"]:
        add_finding(findings, "OK", "M600_ABSENT", "no CFS-inappropriate M600 command was found")

    invalid_tools = [tool for tool in result["tools"] if tool > 3]
    if assume_cfs and invalid_tools:
        add_finding(
            findings,
            "FAIL",
            "CFS_TOOL_OUT_OF_RANGE",
            "tool numbers exceed the four-slot CFS range: "
            + ",".join("T%d" % tool for tool in invalid_tools),
        )
    elif result["tools"]:
        add_finding(
            findings,
            "OK",
            "TOOLS_IN_RANGE",
            "tool commands stay within T0-T3",
        )
    if (
        first_tool_line is not None
        and first_start_line is not None
        and first_tool_line < first_start_line
    ):
        add_finding(
            findings,
            "WARN",
            "TOOL_BEFORE_START_PRINT",
            "first tool command appears before START_PRINT",
            first_tool_line,
        )

    if dangerous_commands:
        for item in dangerous_commands[:5]:
            add_finding(
                findings,
                "FAIL",
                "RAW_CFS_COMMAND",
                "raw CFS/BOX control command is not approved for K2 Pro Combo: "
                + item["command"],
                item["line"],
            )
    else:
        add_finding(
            findings,
            "OK",
            "RAW_CFS_COMMANDS_ABSENT",
            "no raw BOX/M8200 command was found",
        )

    if result["metadata"]["thumbnail"]:
        add_finding(findings, "OK", "PREVIEW_METADATA", "thumbnail metadata is present")
    else:
        add_finding(
            findings,
            "WARN",
            "PREVIEW_METADATA_MISSING",
            "no thumbnail block was found; Fluidd/Mainsail preview may be blank",
        )
    if result["metadata"]["total_layers"]:
        add_finding(findings, "OK", "LAYER_METADATA", "total-layer metadata is present")
    else:
        add_finding(
            findings,
            "WARN",
            "LAYER_METADATA_MISSING",
            "no total-layer metadata was found; layer progress may be unavailable",
        )
    if not result["metadata"]["estimated_time"]:
        add_finding(
            findings,
            "INFO",
            "TIME_METADATA_MISSING",
            "no slicer estimated-time metadata was found",
        )
    if not result["metadata"]["filament_usage"]:
        add_finding(
            findings,
            "INFO",
            "FILAMENT_METADATA_MISSING",
            "no filament-usage metadata was found",
        )

    if commands["exclude_object_define"]:
        add_finding(
            findings,
            "OK",
            "OBJECT_METADATA",
            "%d EXCLUDE_OBJECT_DEFINE command(s) support KAMP/object cancellation"
            % commands["exclude_object_define"],
        )
    else:
        add_finding(
            findings,
            "INFO",
            "OBJECT_METADATA_MISSING",
            "no EXCLUDE_OBJECT_DEFINE command was found; adaptive mesh may use broader bounds",
        )

    for item in result["pressure_advance_values"]:
        if item["value"] < 0.0 or item["value"] > 0.20:
            add_finding(
                findings,
                "WARN",
                "PA_VALUE_IMPLAUSIBLE",
                "pressure advance %.5f is outside the conservative 0.00-0.20 review range"
                % item["value"],
                item["line"],
            )
    if commands["pressure_advance"] and not any(
        row["code"].startswith("PA_") for row in findings
    ):
        add_finding(
            findings,
            "OK",
            "PA_COMMANDS_PLAUSIBLE",
            "pressure-advance command values are syntactically plausible; no calibration was changed",
        )
    elif not commands["pressure_advance"]:
        add_finding(
            findings,
            "INFO",
            "PA_COMMANDS_ABSENT",
            "no executable SET_PRESSURE_ADVANCE command was found; existing printer/profile behavior remains",
        )

    counts = {level: 0 for level in ("OK", "INFO", "WARN", "FAIL")}
    for row in findings:
        counts[row["level"]] += 1
    result["summary"] = counts
    return result


def recent_files(directory, limit):
    rows = []
    for pattern in ("*.gcode", "*.gco", "*.gc"):
        rows.extend(Path(directory).glob(pattern))
    rows = [path for path in rows if path.is_file()]
    rows.sort(key=lambda path: path.stat().st_mtime, reverse=True)
    return rows[: max(1, int(limit))]


def render_report(report):
    lines = [
        "GCODE_PREFLIGHT|file={}|size={}|generated_by={}".format(
            report["file"],
            report.get("size_bytes"),
            report.get("generated_by") or "unknown",
        )
    ]
    for row in report["findings"]:
        where = "|line=%s" % row["line"] if row.get("line") is not None else ""
        lines.append(
            "[{}] {}{}: {}".format(
                row["level"],
                row["code"],
                where,
                row["message"],
            )
        )
    summary = report.get("summary") or {
        level: sum(row["level"] == level for row in report["findings"])
        for level in ("OK", "INFO", "WARN", "FAIL")
    }
    lines.append(
        "GCODE_SUMMARY|OK={OK}|INFO={INFO}|WARN={WARN}|FAIL={FAIL}".format(
            **summary
        )
    )
    return "\n".join(lines)


def selftest():
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        good = root / "good.gcode"
        good.write_text(
            "\n".join(
                (
                    "; generated by Creality_Print V7",
                    "; thumbnail begin 96x96 4",
                    "; AAAA",
                    "; thumbnail end",
                    "; total layers count = 2",
                    "; estimated printing time (normal mode) = 1m",
                    "; filament used [g] = 1.0",
                    "EXCLUDE_OBJECT_DEFINE NAME=test CENTER=1,1 POLYGON=[[0,0],[2,2]]",
                    "START_PRINT EXTRUDER_TEMP=220 BED_TEMP=50",
                    "T0",
                    "SET_PRESSURE_ADVANCE ADVANCE=0.04",
                    "G1 X1 Y1",
                )
            )
            + "\n",
            encoding="utf-8",
        )
        good_report = scan_file(good)
        if good_report["summary"]["WARN"] or good_report["summary"]["FAIL"]:
            raise RuntimeError("good fixture produced warnings or failures")

        bad = root / "bad.gcode"
        bad.write_text(
            "\n".join(
                (
                    "T4",
                    "START_PRINT",
                    "G29",
                    "BED_MESH_CALIBRATE",
                    "M600",
                    "BOX_LOAD_MATERIAL",
                    "SET_PRESSURE_ADVANCE ADVANCE=0.75",
                )
            )
            + "\n",
            encoding="utf-8",
        )
        bad_report = scan_file(bad)
        codes = {row["code"] for row in bad_report["findings"]}
        required = {
            "MESH_COMMAND_DUPLICATE",
            "M600_WITH_CFS",
            "CFS_TOOL_OUT_OF_RANGE",
            "RAW_CFS_COMMAND",
            "PREVIEW_METADATA_MISSING",
            "LAYER_METADATA_MISSING",
            "PA_VALUE_IMPLAUSIBLE",
        }
        if not required.issubset(codes):
            raise RuntimeError("bad fixture did not trigger all required findings")
    print("SELFTEST|OK|G-code metadata, KAMP, CFS and pressure-advance checks")
    return 0


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--file", action="append", help="scan one G-code file")
    action.add_argument(
        "--recent",
        type=int,
        metavar="COUNT",
        help="scan the newest stored G-code files",
    )
    action.add_argument("--selftest", action="store_true")
    parser.add_argument("--directory", default=str(GCODE_DIR))
    parser.add_argument("--json", action="store_true")
    parser.add_argument(
        "--allow-m600",
        action="store_true",
        help="do not apply the K2 Pro Combo CFS M600 warning",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv or sys.argv[1:])
    if args.selftest:
        return selftest()
    paths = [Path(value) for value in (args.file or [])]
    if not paths:
        paths = recent_files(args.directory, args.recent or 5)
    if not paths:
        print("GCODE_PREFLIGHT|INFO|no stored G-code files found in %s" % args.directory)
        return 0
    reports = [scan_file(path, assume_cfs=not args.allow_m600) for path in paths]
    if args.json:
        print(json.dumps(reports, ensure_ascii=True, indent=2, sort_keys=True))
    else:
        print("== K2 Pro Combo G-code preflight ==")
        print("Safety: read-only; files are not changed and no G-code is sent.")
        for index, report in enumerate(reports):
            if index:
                print("")
            print(render_report(report))
    return 1 if any(report.get("summary", {}).get("FAIL") for report in reports) else 0


if __name__ == "__main__":
    raise SystemExit(main())
